name: Build & Publish Debug APK

on:
 workflow_dispatch:
  branches:
   - master
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        cd $GITHUB_WORKSPACE
        git submodule update --init
        chmod +x ./gradlew
        ./gradlew buildStorigDebug
    - name: Upload apk
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: bin/*.apk
